apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "customersetupui.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  tls:
      termination: {{ .Values.route.tls.name }}
      insecureEdgeTerminationPolicy: Allow

  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: {{ .Values.service.weight }}

